[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
    "apt-get update -y", 
    "apt-get install -y build-essential nano xvfb x11-xkb-utils xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic x11-apps",
    "apt-get install -y clang libdbus-1-dev libgtk-3-dev libnotify-dev libgconf2-dev",
    "apt-get install -y libasound2-dev libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev gcc-multilib g++-multilib",
    "apt-get install -y curl gperf bison python3-dbusmock openjdk-8-jre",
    "npm -g config set user root",
    "npm install", 
    "npm install puppeteer --unsafe-perm=true --allow-root",
    "node ./node_modules/puppeteer/install.js", 
    "echo installing!"
]

[phases.build]
cmds = ["echo building!!!"]

[variables]
NODE_ENV = "production"

[start]
cmd = "npm start"
