[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install", "echo installing!"]

[phases.build]
cmds = ["echo building!!!"]

[variables]
NODE_ENV = "production"

[start]
cmd = "npm start"
